language: cpp

git:
  clone: true
  submodules: true
  depth: 1
  quiet: false

env:
  global:
    - SOURCE_DIR=$TRAVIS_BUILD_DIR
    - BUILD_DIR=$SOURCE_DIR/build
    - INSTALL_DIR=$SOURCE_DIR/build/prefix
    - PACKAGE_DIR=$SOURCE_DIR/build/package
    - RUN_DIR=$SOURCE_DIR/build/run
    # - CTEST_EXTRA_ARGS="${CTEST_EXTRA_ARGS:--VV}"

matrix:
  include:

    - name: "Ubuntu 18.04 - UnixODBC - Debug - x86_64 - GCC (system) - Unix Makefiles"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - CC=gcc
        - CXX=g++
        - ODBC_DRIVER_MANAGER=UnixODBC
        - BUILD_TYPE=Debug
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=no
        - CLICKHOUSE_SERVER_IMAGE="yandex/clickhouse-server:19.11.8.46"
      services:
        - docker
      addons:
        apt:
          packages:
            - gcc
            - g++
            - unixodbc
            - unixodbc-bin
            - unixodbc-dev

    - name: "Ubuntu 18.04 - UnixODBC - Release - x86_64 - GCC (system) - Unix Makefiles"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - CC=gcc
        - CXX=g++
        - ODBC_DRIVER_MANAGER=UnixODBC
        - BUILD_TYPE=Release
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=no
        - CLICKHOUSE_SERVER_IMAGE="yandex/clickhouse-server:19.11.8.46"
      services:
        - docker
      addons:
        apt:
          packages:
            - gcc
            - g++
            - unixodbc
            - unixodbc-bin
            - unixodbc-dev

    - name: "Ubuntu 18.04 - UnixODBC - RelWithDebInfo - x86_64 - GCC (system) - Unix Makefiles"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - CC=gcc
        - CXX=g++
        - ODBC_DRIVER_MANAGER=UnixODBC
        - BUILD_TYPE=RelWithDebInfo
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=no
        - CLICKHOUSE_SERVER_IMAGE="yandex/clickhouse-server:19.11.8.46"
      services:
        - docker
      addons:
        apt:
          packages:
            - gcc
            - g++
            - unixodbc
            - unixodbc-bin
            - unixodbc-dev

    - name: "Ubuntu 18.04 - iODBC - RelWithDebInfo - x86_64 - GCC (system) - Unix Makefiles"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - CC=gcc
        - CXX=g++
        - ODBC_DRIVER_MANAGER=iODBC
        - BUILD_TYPE=RelWithDebInfo
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=no
        - CLICKHOUSE_SERVER_IMAGE="yandex/clickhouse-server:19.11.8.46"
      services:
        - docker
      addons:
        apt:
          packages:
            - gcc
            - g++
            - iodbc
            - libiodbc2
            - libiodbc2-dev

    - name: "Ubuntu 18.04 - UnixODBC - RelWithDebInfo - x86_64 - Clang (default) - Unix Makefiles"
      os: linux
      dist: bionic
      compiler: clang
      env:
        - CC=clang
        - CXX=clang++
        - ODBC_DRIVER_MANAGER=UnixODBC
        - BUILD_TYPE=RelWithDebInfo
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=no
        - CLICKHOUSE_SERVER_IMAGE="yandex/clickhouse-server:19.11.8.46"
      services:
        - docker
      addons:
        apt:
          packages:
            - clang
            - unixodbc
            - unixodbc-bin
            - unixodbc-dev

    - name: "Ubuntu 18.04 - iODBC - RelWithDebInfo - x86_64 - Clang (default) - Unix Makefiles
      os: linux
      dist: bionic
      compiler: clang
      env:
        - CC=clang
        - CXX=clang++
        - ODBC_DRIVER_MANAGER=iODBC
        - BUILD_TYPE=RelWithDebInfo
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=no
        - CLICKHOUSE_SERVER_IMAGE="yandex/clickhouse-server:19.11.8.46"
      services:
        - docker
      addons:
        apt:
          packages:
            - clang
            - iodbc
            - libiodbc2
            - libiodbc2-dev

    - name: "Ubuntu 18.04 - UnixODBC - RelWithDebInfo - System third-party libs - x86_64 - GCC (system) - Unix Makefiles"
      os: linux
      dist: bionic
      compiler: gcc
      env:
        - CC=gcc
        - CXX=g++
        - ODBC_DRIVER_MANAGER=UnixODBC
        - BUILD_TYPE=RelWithDebInfo
        - EXTERNAL_THIRD_PARTY=yes
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=no
        - CLICKHOUSE_SERVER_IMAGE="yandex/clickhouse-server:19.11.8.46"
      services:
        - docker
      addons:
        apt:
          packages:
            - gcc
            - g++
            - openssl
            - libssl-dev
            - libpoco-dev
            - googletest
            - unixodbc
            - unixodbc-bin
            - unixodbc-dev

    - name: "Windows Server version 1803 - MDAC - Debug - x64 - MSVC (Visual Studio 2017) - MSBuild"
      os: windows
      language: bash
      env:
        - ODBC_DRIVER_MANAGER=MDAC
        - BUILD_TYPE=Debug
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=yes
        - CMAKE_CONFIGURE_EXTRA_ARGS="-A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 $CMAKE_CONFIGURE_EXTRA_ARGS"
        - VCVARSALL_ARGS=x64

    - name: "Windows Server version 1803 - MDAC - Release - x64 - MSVC (Visual Studio 2017) - MSBuild"
      os: windows
      language: bash
      env:
        - ODBC_DRIVER_MANAGER=MDAC
        - BUILD_TYPE=Release
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=yes
        - CMAKE_CONFIGURE_EXTRA_ARGS="-A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 $CMAKE_CONFIGURE_EXTRA_ARGS"
        - VCVARSALL_ARGS=x64

    - name: "Windows Server version 1803 - MDAC - RelWithDepInfo - x64 - MSVC (Visual Studio 2017) - MSBuild"
      os: windows
      language: bash
      env:
        - ODBC_DRIVER_MANAGER=MDAC
        - BUILD_TYPE=RelWithDepInfo
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=yes
        - CMAKE_CONFIGURE_EXTRA_ARGS="-A x64 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 $CMAKE_CONFIGURE_EXTRA_ARGS"
        - VCVARSALL_ARGS=x64

    - name: "Windows Server version 1803 - MDAC - Debug - x86 - MSVC (Visual Studio 2017) - MSBuild"
      os: windows
      language: bash
      env:
        - ODBC_DRIVER_MANAGER=MDAC
        - BUILD_TYPE=Debug
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=yes
        - CMAKE_CONFIGURE_EXTRA_ARGS="-A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 $CMAKE_CONFIGURE_EXTRA_ARGS"
        - VCVARSALL_ARGS=x86

    - name: "Windows Server version 1803 - MDAC - Release - x86 - MSVC (Visual Studio 2017) - MSBuild"
      os: windows
      language: bash
      env:
        - ODBC_DRIVER_MANAGER=MDAC
        - BUILD_TYPE=Release
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=yes
        - CMAKE_CONFIGURE_EXTRA_ARGS="-A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 $CMAKE_CONFIGURE_EXTRA_ARGS"
        - VCVARSALL_ARGS=x86

    - name: "Windows Server version 1803 - MDAC - RelWithDepInfo - x86 - MSVC (Visual Studio 2017) - MSBuild"
      os: windows
      language: bash
      env:
        - ODBC_DRIVER_MANAGER=MDAC
        - BUILD_TYPE=RelWithDepInfo
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=yes
        - CMAKE_CONFIGURE_EXTRA_ARGS="-A Win32 -DCMAKE_SYSTEM_VERSION=10.0.18362.0 $CMAKE_CONFIGURE_EXTRA_ARGS"
        - VCVARSALL_ARGS=x86

    - name: "macOS 10.14 - iODBC - RelWithDebInfo - x86_64 - AppleClang (Xcode 11.2) - Unix Makefiles"
      os: osx
      osx_image: xcode11.2
      compiler: clang
      env:
        - ODBC_DRIVER_MANAGER=iODBC
        - BUILD_TYPE=RelWithDebInfo
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=no
      addons:
        homebrew:
          packages:
            - libiodbc

    - name: "macOS 10.14 - UnixODBC - RelWithDebInfo - x86_64 - AppleClang (Xcode 11.2) - Unix Makefiles"
      os: osx
      osx_image: xcode11.2
      compiler: clang
      env:
        - ODBC_DRIVER_MANAGER=UnixODBC
        - BUILD_TYPE=RelWithDebInfo
        - EXTERNAL_THIRD_PARTY=no
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=no
      addons:
        homebrew:
          packages:
            - unixodbc

    - name: "macOS 10.14 - iODBC - RelWithDebInfo - System third-party libs - x86_64 - AppleClang (Xcode 11.2) - Unix Makefiles"
      os: osx
      osx_image: xcode11.2
      compiler: clang
      env:
        - ODBC_DRIVER_MANAGER=iODBC
        - BUILD_TYPE=RelWithDebInfo
        - EXTERNAL_THIRD_PARTY=yes
        - PACKAGING=yes
        - TESTING=yes
        - STANDALONE_TESTS_ONLY=no
      addons:
        homebrew:
          packages:
            - openssl
            - poco
            - gtest
            - libiodbc

before_install: |-
  set -Eeo pipefail

  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get update -q
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update
  elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    : # choco upgrade
  fi

install: |-
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo apt-get install -y build-essential cmake perl libdbi-perl libdbd-odbc-perl python python-pyodbc
  elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install cmake perl python@2
    PERL_MM_USE_DEFAULT=1 cpan -T DBD::ODBC
    if [[ "$ODBC_DRIVER_MANAGER" == "iODBC" ]]; then
      # It looks like older version of pyodbc works with iODBC out of the box on macOS:
      # https://github.com/mkleehammer/pyodbc/commit/aa178bfd25afd6fb90c77d054c1bcf0a6aa54411
      pip install --user pyodbc==3.0.7
    else
      pip install --user pyodbc
    fi
  elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    export OLD_VSWHERE=yes

    # TODO: use choco instead of manual download/unpack/env setting, once 3.14+ version
    # is available, since starting from 3.14 WiX Toolset doesn't depend on .NET 3.5,
    # which has problems installing via choco.
    # choco install wixtoolset --yes
    wget https://wixtoolset.org/downloads/v3.14.0.712/wix314-binaries.zip
    powershell -Command Expand-Archive wix314-binaries.zip -DestinationPath wix314-binaries
    export WIX="$(cd wix314-binaries && pwd -W)"
  fi

.clickhouse_start: &clickhouse_start |-
  if [[ "$TESTING" == "yes" ]] && [[ "$STANDALONE_TESTS_ONLY" != "yes" ]]; then
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      docker pull ${CLICKHOUSE_SERVER_IMAGE}
      CLICKHOUSE_SERVER_CONTAINER=$(docker run -d ${CLICKHOUSE_SERVER_IMAGE})
      CLICKHOUSE_SERVER_IP=$(docker inspect -f '{{ .NetworkSettings.IPAddress }}' ${CLICKHOUSE_SERVER_CONTAINER})
      docker ps -a
      docker stats -a --no-stream
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # In macOS, ClickHouse is installed and running as a separate process on this same system.
      # TODO: use native package manager when available.
      $SOURCE_DIR/test/deploy_and_run_clickhouse_macos.sh
      CLICKHOUSE_SERVER_IP=localhost
    fi
  fi

.odbc_configure: &odbc_configure |-
  if [[ "$TESTING" == "yes" ]] && [[ "$STANDALONE_TESTS_ONLY" != "yes" ]]; then
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then

      : # TODO

    else
      if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        ODBC_DRIVER_PATH=$BUILD_DIR/driver/libclickhouseodbc.so
        ODBC_DRIVERW_PATH=$BUILD_DIR/driver/libclickhouseodbcw.so
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        ODBC_DRIVER_PATH=$BUILD_DIR/driver/libclickhouseodbc.dylib
        ODBC_DRIVERW_PATH=$BUILD_DIR/driver/libclickhouseodbcw.dylib
      fi

      export ODBCSYSINI=$RUN_DIR
      export ODBCINSTINI=.odbcinst.ini
      export ODBCINI=$ODBCSYSINI/.odbc.ini
      if [[ "$ODBC_DRIVER_MANAGER" == "iODBC" ]]; then
        # Full path to a custom odbcinst.ini in ODBCINSTINI for iODBC.
        export ODBCINSTINI=$ODBCSYSINI/$ODBCINSTINI
      fi

      cat > $ODBCSYSINI/.odbcinst.ini <<-EOF
  [ODBC]
  Trace     = yes
  TraceFile = ${RUN_DIR}/odbc-driver-manager-trace.log

  [ODBC Drivers]
  clickhouse_driver   = Installed
  clickhouse_driver_w = Installed

  [clickhouse_driver]
  Driver     = ${ODBC_DRIVER_PATH}
  Setup      = ${ODBC_DRIVER_PATH}
  UsageCount = 1

  [clickhouse_driver_w]
  Driver     = ${ODBC_DRIVERW_PATH}
  Setup      = ${ODBC_DRIVERW_PATH}
  UsageCount = 1
  EOF

      cat > $ODBCSYSINI/.odbc.ini <<-EOF
  [ODBC]
  Trace     = yes
  TraceFile = ${RUN_DIR}/odbc-driver-manager-trace.log

  [ODBC Data Sources]
  clickhouse_localhost   = clickhouse_driver
  clickhouse_localhost_w = clickhouse_driver_w

  [clickhouse_localhost]
  Driver        = clickhouse_driver
  Description   = ClickHouse DSN (ANSI, localhost)
  Url           = http://${CLICKHOUSE_SERVER_IP}
  Timeout       = 30
  DriverLog     = yes
  DriverLogFile = ${RUN_DIR}/clickhouse-odbc-driver.log

  [clickhouse_localhost_w]
  Driver        = clickhouse_driver_w
  Description   = ClickHouse DSN (Unicode, localhost)
  Url           = http://${CLICKHOUSE_SERVER_IP}
  Timeout       = 30
  DriverLog     = yes
  DriverLogFile = ${RUN_DIR}/clickhouse-odbc-driver-w.log
  EOF
    fi
  fi

.configure: &configure |-
  CMAKE_CONFIGURE_ARGS="-DTEST_DSN=clickhouse_localhost -DTEST_DSN_W=clickhouse_localhost_w $CMAKE_CONFIGURE_EXTRA_ARGS"
  if [[ "$EXTERNAL_THIRD_PARTY" == "yes" ]]; then
    CMAKE_CONFIGURE_ARGS="-DUNBUNDLED=1 $CMAKE_CONFIGURE_ARGS"
  fi
  if [ -n "$ODBC_DRIVER_MANAGER" ]; then
    CMAKE_CONFIGURE_ARGS="-DODBC_IMPL=$ODBC_DRIVER_MANAGER $CMAKE_CONFIGURE_ARGS"
  fi
  cd $BUILD_DIR
  if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    $SOURCE_DIR/test/vcvars_enabled_bash.sh cmake $CMAKE_CONFIGURE_ARGS $SOURCE_DIR
  else
    cmake $CMAKE_CONFIGURE_ARGS $SOURCE_DIR
  fi

.build: &build |-
  CMAKE_BUILD_ARGS="--config $BUILD_TYPE $CMAKE_BUILD_EXTRA_ARGS -- $CMAKE_BUILD_NATIVE_EXTRA_ARGS"
  cd $BUILD_DIR
  if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    $SOURCE_DIR/test/vcvars_enabled_bash.sh cmake --build . $CMAKE_BUILD_ARGS
  else
    cmake --build . $CMAKE_BUILD_ARGS
  fi

.pack: &pack |-
  if [[ "$PACKAGING" == "yes" ]]; then
    CPACK_ARGS="-C $BUILD_TYPE $CPACK_EXTRA_ARGS"
    cd $BUILD_DIR
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      # 'cpack' is a chocolatey tool, so we use CMake's 'package' target instead
      CPACK_ARGS="--build . --config $BUILD_TYPE --target package -- $CPACK_EXTRA_ARGS"
      $SOURCE_DIR/test/vcvars_enabled_bash.sh cmake $CPACK_ARGS
    else
      cpack $CPACK_ARGS
    fi
  fi

.test: &test |-
  if [[ "$TESTING" == "yes" ]]; then
    CTEST_ARGS="-C $BUILD_TYPE $CTEST_EXTRA_ARGS"
    if [[ "$STANDALONE_TESTS_ONLY" == "yes" ]]; then
      CTEST_ARGS="-R '.*-ut.*' $CTEST_ARGS"
    fi
    cd $BUILD_DIR
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      $SOURCE_DIR/test/vcvars_enabled_bash.sh ctest $CTEST_ARGS
    else
      ctest $CTEST_ARGS
    fi
  fi

before_script: |-
  mkdir -p $SOURCE_DIR
  mkdir -p $BUILD_DIR
  mkdir -p $INSTALL_DIR
  mkdir -p $PACKAGE_DIR
  mkdir -p $RUN_DIR

  if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
    SOURCE_DIR="$(cd $SOURCE_DIR && pwd -W)"
    BUILD_DIR="$(cd $BUILD_DIR && pwd -W)"
    INSTALL_DIR="$(cd $INSTALL_DIR && pwd -W)"
    PACKAGE_DIR="$(cd $PACKAGE_DIR && pwd -W)"
    RUN_DIR="$(cd $RUN_DIR && pwd -W)"
  fi

script:
  - *clickhouse_start
  - *odbc_configure
  - *configure
  - *build
  - *pack
  - *test
